"""Domain layer — core business rules, entities, value objects, ports."""

from coordination_engine.domain.entities import (
    Constraint,
    Event,
    EventParticipant,
    Group,
    PlanningPreferences,
    StateTransition,
    User,
)
from coordination_engine.domain.events import (
    DomainEvent,
    EventCancelled,
    EventCompleted,
    EventCreated,
    EventLocked,
    EventModified,
    EventStateChanged,
    MemoryCollectionRequested,
    ModificationApproved,
    ModificationRejected,
    ModificationRequested,
    ParticipantCancelled,
    ParticipantConfirmed,
    ParticipantJoined,
    ThresholdReached,
)
from coordination_engine.domain.exceptions import (
    BusinessRuleViolation,
    ConcurrencyError,
    DomainError,
    EntityNotFoundError,
    EventLockedError,
    InvalidTransitionError,
    ParticipantActionNotAllowedError,
    ThresholdNotMetError,
)
from coordination_engine.domain.repositories import (
    IConstraintRepository,
    IEventRepository,
    IEventStore,
    IGroupRepository,
    IParticipantRepository,
    IStateTransitionRepository,
    IUserRepository,
)
from coordination_engine.domain.services import (
    EventStateService,
    ParticipantService,
    ScheduleConflictService,
)
from coordination_engine.domain.value_objects import (
    BudgetLevel,
    ConstraintType,
    DatePreset,
    EventState,
    EventType,
    LocationType,
    ParticipantRole,
    ParticipantStatus,
    SchedulingMode,
    TelegramHandle,
    TimeWindow,
    TransportMode,
)

__all__ = [
    # Entities
    "Constraint",
    "Event",
    "EventParticipant",
    "Group",
    "PlanningPreferences",
    "StateTransition",
    "User",
    # Value objects
    "BudgetLevel",
    "ConstraintType",
    "DatePreset",
    "EventState",
    "EventType",
    "LocationType",
    "ParticipantRole",
    "ParticipantStatus",
    "SchedulingMode",
    "TelegramHandle",
    "TimeWindow",
    "TransportMode",
    # Domain events
    "DomainEvent",
    "EventCancelled",
    "EventCompleted",
    "EventCreated",
    "EventLocked",
    "EventModified",
    "EventStateChanged",
    "MemoryCollectionRequested",
    "ModificationApproved",
    "ModificationRejected",
    "ModificationRequested",
    "ParticipantCancelled",
    "ParticipantConfirmed",
    "ParticipantJoined",
    "ThresholdReached",
    # Exceptions
    "BusinessRuleViolation",
    "ConcurrencyError",
    "DomainError",
    "EntityNotFoundError",
    "EventLockedError",
    "InvalidTransitionError",
    "ParticipantActionNotAllowedError",
    "ThresholdNotMetError",
    # Repository ports
    "IConstraintRepository",
    "IEventRepository",
    "IEventStore",
    "IGroupRepository",
    "IParticipantRepository",
    "IStateTransitionRepository",
    "IUserRepository",
    # Domain services
    "EventStateService",
    "ParticipantService",
    "ScheduleConflictService",
]
